os: linux
matrix:
  include:
    - env: TEST="latex build"
      services:
        - docker
      script:
        - make
    - env: TEST=make
      script: |
        set -e
        shopt -s globstar nullglob
        CHECK=( **/Makefile )
        [[ ${#CHECK[@]} -eq 0 ]] && exit
        for f in "${CHECK[@]}"; do
          ( set -e
            cd $(dirname "$f")
            echo "checking $f"
            make --dry-run --warn-undefined-variables
          )
        done
notifications:
  email: false
